// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "fmt"
import "encoding/json"

// IRIS Hub Random Seed Output Body Schema
type ServiceOutput struct {
	// random-seed seed
	Seed string `json:"seed"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ServiceOutput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["seed"]; !ok || v == nil {
		return fmt.Errorf("field seed: required")
	}
	type Plain ServiceOutput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ServiceOutput(plain)
	return nil
}
