// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "fmt"
import "encoding/json"

// Interchain Service Oracle Price Output Body Schema
type ServiceOutput struct {
	// exchange rate
	Rate string `json:"rate"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ServiceOutput) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["rate"]; !ok || v == nil {
		return fmt.Errorf("field rate: required")
	}
	type Plain ServiceOutput
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ServiceOutput(plain)
	return nil
}
